from setuptools import setup, find_packages


with open('README.md') as f:
    readme = f.read()

with open('LICENSE') as f:
    license = f.read()

setup(
    name='stargazers-utils',
    version='0.1.0',
    description='Utilities for processing data files generated by "spencerkimball/stargazers" project.',
    long_description=readme,
    author='Greg Whitaker',
    author_email='greg@netifi.com',
    url='https://github.com/gregwhitaker/stargazers-utils',
    license=license,
    packages=find_packages(exclude=('tests', 'docs'))
)

